### ISSUE TITLE
不能正常编译参考文献

### ISSUE THREAD

**Issue by nathanhsuuu** [MoetaYuko/NPU_PhD_proposal#1]
在编译参考文献的时候会出现
I found no \citation commands BibTeX [Ln 1, Col 1]
I found no \bibdata commands BibTeX [Ln 1, Col 1]
I found no \bibstyle commands BibTeX [Ln 1, Col 1]
即便是原文件直接编译也会出现。

**Comment by moetayuko** [comment]
texlive 2024 linux 可正常编译

**Comment by nathanhsuuu** [comment]
我这边试了一下win11和mac（额外改了cls字体），都没法编译参考文献

**Comment by nathanhsuuu** [comment]
> 我这边试了一下win11和mac（额外改了cls字体），都没法编译参考文献

查看cls，已解决，我未使用biber，改为bibtex后成功。打扰大佬了，非常感谢。
